version: "3.7"

services:
  app:
    build: .
    container_name: xDRBasedProject
    ports:
      - "8000:8000"
    depends_on:
      - postgresdb
    networks:
      - xDRBasedNetwork

  postgresdb:
    image: postgres:latest
    container_name: xDRBasedProjectDB
    environment:
      POSTGRES_DB: xdrDb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5433:5432"
    networks:
      - xDRBasedNetwork
    volumes:
      - pg-data:/var/lib/postgresql/data


networks:
  xDRBasedNetwork:
    name: xDRBasedNetwork

volumes:
  pg-data: